Explain why yarn is more preferred than npm
Currently it's not possible to run encore after installing dependencies with `NPM`. Error in console:

```
$ npx encore
/node_modules/@symfony/webpack-encore/bin/encore.js:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

Only after using yarn the problem was solved.

The lock file is a must, we will know everyone's dependencies are in the same situation.
Unfortunately the `package-lock.json` file from `NPM@5` is not supported by `yarn`
https://github.com/yarnpkg/yarn/issues/3614

Related:
https://github.com/symfony/webpack-encore/issues/39