Added node_paths /usr/lib/node_modules REQUIRED
I was testing, testing and testing one and another method or posibility, until I reached that page: https://github.com/kriswallsmith/assetic/issues/185 that opened my eyes, and one value was missing:

node_paths /usr/lib/node_modules

I continously received:
[exception] 500 | Internal Server Error | Assetic\Exception\FilterException
[message] An error occurred while running:
&#039;/usr/bin/node&#039; &#039;/tmp/assetic_styluswWvcnS&#039;
Error Output:
module.js:340
throw err;
^
Error: Cannot find module &#039;stylus&#039; 

so, this fixes and finishes my 6 hours quest.