Update service_subscribers_locators.rst
Added the missing use statement, even though Symfony is nice enough to give the missing use statement on a silver platter.
I did not check versions going forward in the documentation.
```
  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Reference" from namespace "DealExpress\ApiBundle\DependencyInjection\Compiler".                                                                                                                                                                    
  Did you forget a "use" statement for e.g. "Google_Service_Compute_Reference", "phpDocumentor\Reflection\DocBlock\Tags\Reference\Reference", "Symfony\Component\DependencyInjection\Reference" or "Symfony\Component\Validator\Tests\Fixtures\Reference"?
```