Added node_paths /usr/lib/node_modules REQUIRED
I proposed this patch for branch 2.2 and is already patched https://github.com/symfony/symfony-docs/commit/f1483240e88722bb53b8d22bd479944ba48d8047, please apply to branch 2.3

I was testing, testing and testing one and another method or posibility, until I reached that page: https://github.com/kriswallsmith/assetic/issues/185 that opened my eyes, and one value was missing:

node_paths /usr/lib/node_modules

I continously received:
[exception] 500 | Internal Server Error | Assetic\Exception\FilterException
[message] An error occurred while running:
&#39;/usr/bin/node&#39; &#39;/tmp/assetic_styluswWvcnS&#39;
Error Output:
module.js:340
throw err;
^
Error: Cannot find module &#39;stylus&#39;

so, this fixes and finishes my 6 hours quest.